name: Deploy to Screeps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Project Imperium
        run: npm run build
      
      - name: Verify build output
        run: |
          if [ ! -f dist/main.js ]; then
            echo "❌ Build failed - dist/main.js not found"
            exit 1
          fi
          echo "✅ Build successful - dist/main.js created"
          ls -lh dist/main.js
      
      - name: Deploy to Screeps
        env:
          SCREEPS_TOKEN: ${{ secrets.SCREEPS_TOKEN }}
          SCREEPS_BRANCH: ${{ secrets.SCREEPS_BRANCH || 'main' }}
        run: |
          echo "🚀 Deploying Project Imperium to Screeps..."
          if [ -z "$SCREEPS_TOKEN" ]; then
            echo "⚠️  SCREEPS_TOKEN not configured in repository secrets"
            echo "ℹ️  Build completed successfully but deployment skipped"
            exit 0
          fi
          
          # Install screeps deployment tool if needed
          npm install -g screeps-api
          
          # Deploy using screeps-api
          # This is a placeholder - adjust based on your preferred deployment method
          echo "✅ Project Imperium ready for deployment"
          echo "📦 Size: $(wc -c < dist/main.js) bytes"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: project-imperium-build
          path: dist/
          retention-days: 7
